// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateConsumer(arg1) {
  return window['go']['main']['App']['CreateConsumer'](arg1);
}

export function CreateKVBucket(arg1) {
  return window['go']['main']['App']['CreateKVBucket'](arg1);
}

export function CreateStream(arg1) {
  return window['go']['main']['App']['CreateStream'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConsumer(arg1, arg2) {
  return window['go']['main']['App']['DeleteConsumer'](arg1, arg2);
}

export function DeleteKVBucket(arg1) {
  return window['go']['main']['App']['DeleteKVBucket'](arg1);
}

export function DeleteKVEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteKVEntry'](arg1, arg2);
}

export function DeleteStream(arg1) {
  return window['go']['main']['App']['DeleteStream'](arg1);
}

export function DeleteStreamMsg(arg1, arg2) {
  return window['go']['main']['App']['DeleteStreamMsg'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetActiveSubscriptions() {
  return window['go']['main']['App']['GetActiveSubscriptions']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetKVBucket(arg1) {
  return window['go']['main']['App']['GetKVBucket'](arg1);
}

export function GetKVEntry(arg1, arg2) {
  return window['go']['main']['App']['GetKVEntry'](arg1, arg2);
}

export function GetKVHistory(arg1, arg2) {
  return window['go']['main']['App']['GetKVHistory'](arg1, arg2);
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSetting(arg1, arg2) {
  return window['go']['main']['App']['GetSetting'](arg1, arg2);
}

export function GetStreamMsg(arg1, arg2) {
  return window['go']['main']['App']['GetStreamMsg'](arg1, arg2);
}

export function GetStreamMsgsBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStreamMsgsBatch'](arg1, arg2, arg3, arg4);
}

export function ListConsumers(arg1) {
  return window['go']['main']['App']['ListConsumers'](arg1);
}

export function ListKVBuckets() {
  return window['go']['main']['App']['ListKVBuckets']();
}

export function ListKVEntries(arg1) {
  return window['go']['main']['App']['ListKVEntries'](arg1);
}

export function ListStreams() {
  return window['go']['main']['App']['ListStreams']();
}

export function PublishMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishMessage'](arg1, arg2, arg3, arg4);
}

export function PurgeKVDeletes(arg1) {
  return window['go']['main']['App']['PurgeKVDeletes'](arg1);
}

export function PurgeKVEntry(arg1, arg2) {
  return window['go']['main']['App']['PurgeKVEntry'](arg1, arg2);
}

export function PurgeStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['PurgeStream'](arg1, arg2, arg3);
}

export function PutKVEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['PutKVEntry'](arg1, arg2, arg3);
}

export function RequestMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RequestMessage'](arg1, arg2, arg3, arg4);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['main']['App']['Subscribe'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}

export function UpdateKVBucket(arg1) {
  return window['go']['main']['App']['UpdateKVBucket'](arg1);
}

export function UpdateStream(arg1) {
  return window['go']['main']['App']['UpdateStream'](arg1);
}
