// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {natsmanager} from '../models';

export function Connect(arg1:storage.ConnectionProfile):Promise<natsmanager.ServerStatus>;

export function CreateConsumer(arg1:natsmanager.ConsumerCreateParams):Promise<void>;

export function CreateKVBucket(arg1:natsmanager.KVBucketCreateParams):Promise<void>;

export function CreateStream(arg1:natsmanager.StreamCreateParams):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConsumer(arg1:string,arg2:string):Promise<void>;

export function DeleteKVBucket(arg1:string):Promise<void>;

export function DeleteKVEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteStream(arg1:string):Promise<void>;

export function DeleteStreamMsg(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveSubscriptions():Promise<Array<natsmanager.SubscriptionInfo>>;

export function GetConnectionStatus():Promise<natsmanager.ServerStatus>;

export function GetKVBucket(arg1:string):Promise<natsmanager.KVBucketInfo>;

export function GetKVEntry(arg1:string,arg2:string):Promise<natsmanager.KVEntryInfo>;

export function GetKVHistory(arg1:string,arg2:string):Promise<Array<natsmanager.KVEntryInfo>>;

export function GetSavedConnections():Promise<Array<storage.ConnectionProfile>>;

export function GetSetting(arg1:string,arg2:string):Promise<string>;

export function GetStreamMsg(arg1:string,arg2:number):Promise<natsmanager.JSStoredMsg>;

export function GetStreamMsgsBatch(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<natsmanager.JSStoredMsg>>;

export function ListConsumers(arg1:string):Promise<Array<natsmanager.JSConsumerInfo>>;

export function ListKVBuckets():Promise<Array<natsmanager.KVBucketInfo>>;

export function ListKVEntries(arg1:string):Promise<Array<natsmanager.KVEntryInfo>>;

export function ListStreams():Promise<Array<natsmanager.JSStreamInfo>>;

export function PublishMessage(arg1:string,arg2:string,arg3:Record<string, Array<string>>,arg4:string):Promise<void>;

export function PurgeKVDeletes(arg1:string):Promise<void>;

export function PurgeKVEntry(arg1:string,arg2:string):Promise<void>;

export function PurgeStream(arg1:string,arg2:string,arg3:number):Promise<void>;

export function PutKVEntry(arg1:string,arg2:string,arg3:string):Promise<number>;

export function RequestMessage(arg1:string,arg2:Record<string, Array<string>>,arg3:string,arg4:number):Promise<natsmanager.PubSubMessage>;

export function SaveConnection(arg1:storage.ConnectionProfile):Promise<void>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:string):Promise<natsmanager.SubscriptionInfo>;

export function TestConnection(arg1:storage.ConnectionProfile):Promise<natsmanager.ServerStatus>;

export function Unsubscribe(arg1:string):Promise<void>;

export function UpdateKVBucket(arg1:natsmanager.KVBucketCreateParams):Promise<void>;

export function UpdateStream(arg1:natsmanager.StreamCreateParams):Promise<void>;
