// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {natsmanager} from '../models';
import {kafkamanager} from '../models';
import {rabbitmqmanager} from '../models';
import {sqsmanager} from '../models';
import {mcpserver} from '../models';

export function ChangeSQSMessageVisibility(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Connect(arg1:storage.ConnectionProfile):Promise<natsmanager.ServerStatus>;

export function CreateConsumer(arg1:natsmanager.ConsumerCreateParams):Promise<void>;

export function CreateKVBucket(arg1:natsmanager.KVBucketCreateParams):Promise<void>;

export function CreateKafkaTopic(arg1:kafkamanager.CreateTopicParams):Promise<void>;

export function CreateRabbitMQBinding(arg1:rabbitmqmanager.CreateBindingParams):Promise<void>;

export function CreateRabbitMQExchange(arg1:rabbitmqmanager.CreateExchangeParams):Promise<rabbitmqmanager.RMQExchangeSummary>;

export function CreateRabbitMQQueue(arg1:rabbitmqmanager.CreateQueueParams):Promise<rabbitmqmanager.RMQQueueSummary>;

export function CreateSQSQueue(arg1:sqsmanager.CreateQueueParams):Promise<sqsmanager.SQSQueueSummary>;

export function CreateStream(arg1:natsmanager.StreamCreateParams):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConsumer(arg1:string,arg2:string):Promise<void>;

export function DeleteKVBucket(arg1:string):Promise<void>;

export function DeleteKVEntry(arg1:string,arg2:string):Promise<void>;

export function DeleteKafkaConsumerGroup(arg1:string):Promise<void>;

export function DeleteKafkaRecordsUpTo(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DeleteKafkaTopic(arg1:string):Promise<void>;

export function DeleteRabbitMQBinding(arg1:rabbitmqmanager.CreateBindingParams):Promise<void>;

export function DeleteRabbitMQExchange(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRabbitMQQueue(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function DeleteSQSMessage(arg1:string,arg2:string):Promise<void>;

export function DeleteSQSQueue(arg1:string):Promise<void>;

export function DeleteStream(arg1:string):Promise<void>;

export function DeleteStreamMsg(arg1:string,arg2:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveSubscriptions():Promise<Array<natsmanager.SubscriptionInfo>>;

export function GetConnectionStatus():Promise<natsmanager.ServerStatus>;

export function GetKVBucket(arg1:string):Promise<natsmanager.KVBucketInfo>;

export function GetKVEntry(arg1:string,arg2:string):Promise<natsmanager.KVEntryInfo>;

export function GetKVHistory(arg1:string,arg2:string):Promise<Array<natsmanager.KVEntryInfo>>;

export function GetKafkaBrokerConfigs(arg1:number):Promise<Array<kafkamanager.BrokerConfigEntry>>;

export function GetKafkaBrokers():Promise<Array<kafkamanager.BrokerInfo>>;

export function GetKafkaClusterStatus():Promise<kafkamanager.KafkaClusterStatus>;

export function GetKafkaConsumerGroupDetails(arg1:string):Promise<kafkamanager.ConsumerGroupDetailInfo>;

export function GetKafkaMessages(arg1:kafkamanager.GetKafkaMessagesParams):Promise<Array<kafkamanager.KafkaRecord>>;

export function GetKafkaTopicDetails(arg1:string):Promise<kafkamanager.TopicDetailInfo>;

export function GetMCPServerStatus():Promise<mcpserver.ServerStatus>;

export function GetRabbitMQExchangeDetails(arg1:string,arg2:string):Promise<rabbitmqmanager.RMQExchangeDetail>;

export function GetRabbitMQOverview():Promise<rabbitmqmanager.RMQOverview>;

export function GetRabbitMQQueueDetails(arg1:string,arg2:string):Promise<rabbitmqmanager.RMQQueueDetail>;

export function GetRabbitMQStatus():Promise<rabbitmqmanager.RMQClusterStatus>;

export function GetSQSQueueDetails(arg1:string):Promise<sqsmanager.SQSQueueDetail>;

export function GetSQSStatus():Promise<sqsmanager.SQSClusterStatus>;

export function GetSavedConnections():Promise<Array<storage.ConnectionProfile>>;

export function GetSetting(arg1:string,arg2:string):Promise<string>;

export function GetStreamMsg(arg1:string,arg2:number):Promise<natsmanager.JSStoredMsg>;

export function GetStreamMsgsBatch(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<natsmanager.JSStoredMsg>>;

export function ListConsumers(arg1:string):Promise<Array<natsmanager.JSConsumerInfo>>;

export function ListKVBuckets():Promise<Array<natsmanager.KVBucketInfo>>;

export function ListKVEntries(arg1:string):Promise<Array<natsmanager.KVEntryInfo>>;

export function ListKafkaConsumerGroups():Promise<Array<kafkamanager.ConsumerGroupSummary>>;

export function ListKafkaTopics(arg1:boolean):Promise<Array<kafkamanager.TopicSummary>>;

export function ListRabbitMQBindings(arg1:string):Promise<Array<rabbitmqmanager.RMQBindingInfo>>;

export function ListRabbitMQExchanges(arg1:string):Promise<Array<rabbitmqmanager.RMQExchangeSummary>>;

export function ListRabbitMQNodes():Promise<Array<rabbitmqmanager.RMQNodeInfo>>;

export function ListRabbitMQQueues(arg1:string):Promise<Array<rabbitmqmanager.RMQQueueSummary>>;

export function ListRabbitMQVHosts():Promise<Array<rabbitmqmanager.RMQVHostInfo>>;

export function ListSQSQueues(arg1:string):Promise<Array<sqsmanager.SQSQueueSummary>>;

export function ListStreams():Promise<Array<natsmanager.JSStreamInfo>>;

export function PeekRabbitMQMessages(arg1:rabbitmqmanager.PeekRMQMessagesParams):Promise<Array<rabbitmqmanager.RMQMessage>>;

export function PollSQSMessages(arg1:sqsmanager.PollSQSMessagesParams):Promise<Array<sqsmanager.SQSMessage>>;

export function ProduceKafkaRecord(arg1:kafkamanager.ProduceKafkaRecordParams):Promise<kafkamanager.ProduceRecordResult>;

export function PublishMessage(arg1:string,arg2:string,arg3:Record<string, Array<string>>,arg4:string):Promise<void>;

export function PublishRabbitMQMessage(arg1:rabbitmqmanager.PublishRMQMessageParams):Promise<rabbitmqmanager.PublishRMQMessageResult>;

export function PurgeKVDeletes(arg1:string):Promise<void>;

export function PurgeKVEntry(arg1:string,arg2:string):Promise<void>;

export function PurgeKafkaPartition(arg1:string,arg2:number):Promise<void>;

export function PurgeKafkaTopic(arg1:string):Promise<void>;

export function PurgeRabbitMQQueue(arg1:string,arg2:string):Promise<number>;

export function PurgeSQSQueue(arg1:string):Promise<void>;

export function PurgeStream(arg1:string,arg2:string,arg3:number):Promise<void>;

export function PutKVEntry(arg1:string,arg2:string,arg3:string):Promise<number>;

export function RedriveDLQ(arg1:sqsmanager.RedriveDLQParams):Promise<sqsmanager.RedriveDLQResult>;

export function RedriveRabbitMQDLQ(arg1:rabbitmqmanager.RedriveDLQParams):Promise<rabbitmqmanager.RedriveDLQResult>;

export function RequestMessage(arg1:string,arg2:Record<string, Array<string>>,arg3:string,arg4:number):Promise<natsmanager.PubSubMessage>;

export function ResetKafkaConsumerGroupOffsets(arg1:kafkamanager.ResetOffsetsParams):Promise<void>;

export function SaveConnection(arg1:storage.ConnectionProfile):Promise<void>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SendSQSMessage(arg1:sqsmanager.SendSQSMessageParams):Promise<sqsmanager.SendSQSMessageResult>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function StartKafkaLiveTail(arg1:string,arg2:Array<number>):Promise<void>;

export function StartMCPServer(arg1:number,arg2:boolean):Promise<void>;

export function StartRabbitMQLiveConsume(arg1:rabbitmqmanager.ConsumeRMQMessagesParams):Promise<void>;

export function StartSQSLivePoll(arg1:sqsmanager.PollSQSMessagesParams):Promise<void>;

export function StopKafkaLiveTail():Promise<void>;

export function StopMCPServer():Promise<void>;

export function StopRabbitMQLiveConsume():Promise<void>;

export function StopSQSLivePoll():Promise<void>;

export function Subscribe(arg1:string,arg2:string,arg3:string):Promise<natsmanager.SubscriptionInfo>;

export function TestConnection(arg1:storage.ConnectionProfile):Promise<natsmanager.ServerStatus>;

export function Unsubscribe(arg1:string):Promise<void>;

export function UpdateKVBucket(arg1:natsmanager.KVBucketCreateParams):Promise<void>;

export function UpdateKafkaTopicConfigs(arg1:string,arg2:Record<string, string>):Promise<void>;

export function UpdateKafkaTopicPartitions(arg1:string,arg2:number):Promise<void>;

export function UpdateSQSQueueAttributes(arg1:string,arg2:Record<string, string>):Promise<void>;

export function UpdateSQSQueueTags(arg1:string,arg2:Record<string, string>,arg3:Array<string>):Promise<void>;

export function UpdateStream(arg1:natsmanager.StreamCreateParams):Promise<void>;
